### ISSUE TITLE
User edit path issues

### ISSUE THREAD

**Issue by confact** [andrewculver/koudoku#113]
Getting this when i visit pricing:
```ruby
Showing /vagrant/app/views/layouts/application.html.erb where line #54 raised:
undefined local variable or method `edit_user_registration_path' for #<#<Class:0x0000000915b950>:0x0000000915a7a8>
  <%= link_to(t('menu.admin'), '/admin/', class: 'item') %>
<% end %>
<% if current_user.username.present? %>
  <%= link_to(current_user.username, edit_user_registration_path, class: 'item') %>
<% else %>
  <%= link_to(t('menu.edit'), edit_user_registration_path, class: 'item') %>
<% end %>
```
All other pages work, with this layout.

This is the whole trace:
```
app/views/layouts/application.html.erb:54:in `_app_views_layouts_application_html_erb___2967155160843082001_76010280'
/home.rvm/gems/ruby-2.1.4/gems/actionview-4.1.6/lib/action_view/template.rb:145:in `block in render'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
/home.rvm/gems/ruby-2.1.4/gems/actionview-4.1.6/lib/action_view/template.rb:339:in `instrument'
/home.rvm/gems/ruby-2.1.4/gems/actionview-4.1.6/lib/action_view/template.rb:143:in `render'
/home.rvm/gems/ruby-2.1.4/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/profiling_methods.rb:106:in `block in profile_method'
/home.rvm/gems/ruby-2.1.4/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:67:in `render_with_layout'
/home.rvm/gems/ruby-2.1.4/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:53:in `render_template'
/home.rvm/gems/ruby-2.1.4/gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:17:in `render'
/home.rvm/gems/ruby-2.1.4/gems/actionview-4.1.6/lib/action_view/renderer/renderer.rb:42:in `render_template'
/home.rvm/gems/ruby-2.1.4/gems/actionview-4.1.6/lib/action_view/renderer/renderer.rb:23:in `render'
/home.rvm/gems/ruby-2.1.4/gems/actionview-4.1.6/lib/action_view/rendering.rb:99:in `_render_template'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/home.rvm/gems/ruby-2.1.4/gems/actionview-4.1.6/lib/action_view/rendering.rb:82:in `render_to_body'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/abstract_controller/rendering.rb:25:in `render'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:16:in `render'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
/home.rvm/gems/ruby-2.1.4/gems/searchkick-0.8.7/lib/searchkick/logging.rb:112:in `cleanup_view_runtime'
/home.rvm/gems/ruby-2.1.4/gems/activerecord-4.1.6/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:40:in `render'
/home.rvm/gems/ruby-2.1.4/gems/meta-tags-2.0.0/lib/meta_tags/controller_helper.rb:26:in `render_with_meta_tags'
/home.rvm/gems/ruby-2.1.4/gems/remotipart-1.2.1/lib/remotipart/render_overrides.rb:14:in `render_with_remotipart'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:189:in `process_action'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/home.rvm/gems/ruby-2.1.4/gems/searchkick-0.8.7/lib/searchkick/logging.rb:107:in `process_action'
/home.rvm/gems/ruby-2.1.4/gems/activerecord-4.1.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:136:in `process'
/home.rvm/gems/ruby-2.1.4/gems/actionview-4.1.6/lib/action_view/rendering.rb:30:in `process'
/home.rvm/gems/ruby-2.1.4/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/profiling_methods.rb:106:in `block in profile_method'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal.rb:196:in `dispatch'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_controller/metal.rb:232:in `block in action'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:82:in `call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:50:in `call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:73:in `block in call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `each'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:678:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rack-pjax-0.8.0/lib/rack/pjax.rb:12:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/home.rvm/gems/ruby-2.1.4/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/home.rvm/gems/ruby-2.1.4/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/home.rvm/gems/ruby-2.1.4/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
/home.rvm/gems/ruby-2.1.4/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
/home.rvm/gems/ruby-2.1.4/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/flash.rb:254:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
/home.rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activerecord-4.1.6/lib/active_record/query_cache.rb:36:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rails-dev-tweaks-1.2.0/lib/rails_dev_tweaks/granular_autoload/middleware.rb:36:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/rack/logger.rb:38:in `call_app'
/home.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/rack/logger.rb:22:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/static.rb:64:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/profiler.rb:276:in `call'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/engine.rb:514:in `call'
/home.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/application.rb:144:in `call'
/home.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/railtie.rb:194:in `public_send'
/home.rvm/gems/ruby-2.1.4/gems/railties-4.1.6/lib/rails/railtie.rb:194:in `method_missing'
/home.rvm/gems/ruby-2.1.4/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/home.rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
/home.rvm/gems/ruby-2.1.4/gems/puma-2.11.2/lib/puma/server.rb:507:in `handle_request'
/home.rvm/gems/ruby-2.1.4/gems/puma-2.11.2/lib/puma/server.rb:375:in `process_client'
/home.rvm/gems/ruby-2.1.4/gems/puma-2.11.2/lib/puma/server.rb:262:in `block in run'
/home.rvm/gems/ruby-2.1.4/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `call'
/home.rvm/gems/ruby-2.1.4/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by yas4891** [comment]
Please try `main_app. edit_user_registration_path` and let me know if that works

**Comment by confact** [comment]
@yas4891 That worked, thanks. Thought i just needed to use the main_app in the view and not in the layout. IMO is that weird to be forced to use main_app in rest of the app/layout.

Closing this because that made the trick anyway.
