### ISSUE TITLE
NoMethodError (undefined method `encoding' for nil:NilClass)

### ISSUE THREAD

**Issue by cotorusso** [andrewculver/koudoku#134]
i create a new user without credit card from devise registrationscontroller and i create new subscription with this code:

subscription = Subscription.new
subscription.plan_id = 1
subscription.user_id = @user.id
subscription.save

i receive this error:

undefined method `encoding' for nil:NilClass

can you help me?

**Comment by shawila** [comment]
Same here. Just using the default views to test out adding a subscription.
I have the newest code for the gem, and checked that `config/initializers/koudoku.rb` has `Stripe.api_version = '2015-01-11'`.

**Comment by shawila** [comment]
Ok checking my stripe dashboard I found the API version has been updated to `2015-10-16`. Updating the initializer fixed the issue. Thanks.

**Comment by shawila** [comment]
As a side note, this worked fine when the owner is the `user` model.
When I changed the owner to the `organization` model, I got another error that `cards` is undefined. Setting back the version to `2015-01-11` solved it.

Not sure if that is relevant or not.

**Comment by bval** [comment]
I just ran up against this and the root of the problem was stripe.js not initializing properly. The `subscriptions/card` partial contains some javascript that has a jQuery dependency. If you load your Javascript dependencies in the bottom of your layout, it's quite probable that jQuery will not be initialized before that in-page Javascript from Koudoku executes. I worked around the problem by customizing the `subscriptions/card` partial to surround the raw javascript with a `content_for` block that renders in the appropriate place in my layout. Without stripe.js, there's no token to send with the Stripe API request and thus the response doesn't contain any cards or a default_card, leading to the problem experienced.

**Comment by georgetmayorga** [comment]
@bval can you expand on your solution? I have this same error and the transaction is going through succesfully in my stripe dashboard returning a 200 succesful transaction. I get this error right before it's saving to the subscription in `concerns/subscription.rb:99`. Is this a different pattern from your issue?

```
stripe (1.41.0) lib/stripe/list_object.rb:67:in `retrieve'
koudoku (1.2.4) app/concerns/koudoku/subscription.rb:99:in `processing!'
activesupport (4.2.5) lib/active_support/callbacks.rb:432:in `block in make_lambda'
activesupport (4.2.5) lib/active_support/callbacks.rb:164:in `call'
activesupport (4.2.5) lib/active_support/callbacks.rb:164:in `block in halting'
activesupport (4.2.5) lib/active_support/callbacks.rb:504:in `call'
activesupport (4.2.5) lib/active_support/callbacks.rb:504:in `block in call'
activesupport (4.2.5) lib/active_support/callbacks.rb:504:in `each'
```

**Comment by bval** [comment]
@georgetmayorga sure. In the card partial there is a script tag you [can see here](https://github.com/andrewculver/koudoku/blob/master/app/views/koudoku/subscriptions/_card.html.erb#L52). That Javascript has an explicit jQuery dependency (witness the `$`s liberally scattered everywhere). I have modified my card partial to wrap that whole script tag in a `content_for` block like this:
```
<% content_for :body_close do %>
  <script type="text/javascript">
    // All this code taken from Stripe's own examples at:
    // https://stripe.com/docs/tutorials/forms .

    function stripeResponseHandler(status, response) {
    [...]
  </script>
<% end %>
```

Then in my application layout I have something like:
```
    <%= javascript_include_tag 'application' %>
    <%= yield :body_close %>
```

My application.js requires jQuery, ensuring that the jQuery include comes before the use of it in that Javascript from the card partial.

Hope this helps.
