### ISSUE TITLE
customer.default_card returning nil

### ISSUE THREAD

**Issue by mattyb** [andrewculver/koudoku#136]
When creating a subscription, I get this trace
```
NoMethodError in Koudoku::SubscriptionsController#create
undefined method `encoding' for nil:NilClass

/home/vagrant/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/cgi/util.rb:8:in `escape'
stripe (1.30.2) lib/stripe/list_object.rb:66:in `retrieve'
koudoku (1.2.4) app/concerns/koudoku/subscription.rb:99:in `processing!'
activesupport (4.1.13) lib/active_support/callbacks.rb:429:in `block in make_lambda'
activesupport (4.1.13) lib/active_support/callbacks.rb:161:in `call'
activesupport (4.1.13) lib/active_support/callbacks.rb:161:in `block in halting'
activesupport (4.1.13) lib/active_support/callbacks.rb:501:in `call'
activesupport (4.1.13) lib/active_support/callbacks.rb:501:in `block in call'
activesupport (4.1.13) lib/active_support/callbacks.rb:501:in `each'
activesupport (4.1.13) lib/active_support/callbacks.rb:501:in `call'
activesupport (4.1.13) lib/active_support/callbacks.rb:86:in `run_callbacks'
activerecord (4.1.13) lib/active_record/callbacks.rb:302:in `create_or_update'
activerecord (4.1.13) lib/active_record/persistence.rb:103:in `save'
activerecord (4.1.13) lib/active_record/validations.rb:51:in `save'
activerecord (4.1.13) lib/active_record/attribute_methods/dirty.rb:21:in `save'
activerecord (4.1.13) lib/active_record/transactions.rb:268:in `block (2 levels) in save'
activerecord (4.1.13) lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
activerecord (4.1.13) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
activerecord (4.1.13) lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
activerecord (4.1.13) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
activerecord (4.1.13) lib/active_record/transactions.rb:208:in `transaction'
activerecord (4.1.13) lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
activerecord (4.1.13) lib/active_record/transactions.rb:268:in `block in save'
activerecord (4.1.13) lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
activerecord (4.1.13) lib/active_record/transactions.rb:267:in `save'
newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/active_record_helper.rb:26:in `block in save'
newrelic_rpm (3.13.2.302) lib/new_relic/agent/transaction.rb:807:in `with_database_metric_name'
newrelic_rpm (3.13.2.302) lib/new_relic/agent.rb:572:in `with_database_metric_name'
newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/active_record_helper.rb:25:in `save'
koudoku (1.2.4) app/controllers/koudoku/subscriptions_controller.rb:122:in `create'
```

**Comment by yas4891** [comment]
Please make sure you use the proper API version as described here: https://github.com/andrewculver/koudoku/issues/122#issuecomment-115109987

**Comment by mattyb** [comment]
I'm using koudoku version 1.2.4 with the default initializer file. it includes 
```
Stripe.api_version = '2015-01-11'
```

**Comment by mattyb** [comment]
```
$ rails console
Loading development environment (Rails 4.1.13)
[1] pry(main)> Stripe.api_version
=> "2015-01-11"
```

**Comment by mattyb** [comment]
The posts going to stripe do not seem to include card information. Here are the two logged URLs and parsed bodies from stripe dashboard. Both list the API version as above and have a Source of `Stripe/v1 RubyBindings/1.30.2`

`POST /v1/customers`
```
{
description: "Matty"
email: "test@gmail.com"
}
```
`POST /v1/customers/cus_7CuOXTRdpefnWU/subscription`
```
{
plan: "small_shared"
prorate: "true"
}
```

**Comment by mattyb** [comment]
Tracked this down to a javascript issue. jquery was loaded at the bottom of my page and not at the head, which caused `$` in body script to be undefined.

**Comment by yas4891** [comment]
Great debugging, Matthew!
