### ISSUE TITLE
`binread': No such file or directory - /app/models/plan.rb (Errno::ENOENT)

### ISSUE THREAD

**Issue by azlantaher88** [andrewculver/koudoku#38]
Keep getting this error while running the generator, Its strange I dont see any issue here.

**Comment by funkdified** [comment]
```
funkdified@funktop ~/rails_projects/hearingtracker $ rails g koudoku:install user      create  config/initializers/koudoku.rb
    generate  model
/home/funkdified/.rvm/rubies/ruby-2.1.2/bin/ruby: No such file or directory -- bin/rails (LoadError)
        gsub  app/models/subscription.rb
/home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:231:in `binread': No such file or directory @ rb_sysopen - /home/funkdified/rails_projects/hearingtracker/app/models/subscription.rb (Errno::ENOENT)
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:231:in `gsub_file'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/koudoku-0.0.11/lib/generators/koudoku/install_generator.rb:42:in `install'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/railties-4.2.0.rc2/lib/rails/generators.rb:157:in `invoke'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/railties-4.2.0.rc2/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/activesupport-4.2.0.rc2/lib/active_support/dependencies.rb:274:in `require'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/activesupport-4.2.0.rc2/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/activesupport-4.2.0.rc2/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/activesupport-4.2.0.rc2/lib/active_support/dependencies.rb:274:in `require'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/railties-4.2.0.rc2/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/railties-4.2.0.rc2/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/railties-4.2.0.rc2/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/railties-4.2.0.rc2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/railties-4.2.0.rc2/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Comment by funkdified** [comment]
I copied the contents of `app/concerns/koudoku/subscription.rb` and `app/concerns/koudoku/plan.rb` into matching models in my app, and created a blank `coupon.rb` model to which ` has_many :subscriptions` was added by the generator. `has_one :subscription` was also added to my user model...

I was able to run the generator to completion but no migrations were added.
