### ISSUE TITLE
undefined method `encoding' for nil:NilClass

### ISSUE THREAD

**Issue by jackerman09** [andrewculver/koudoku#44]
I am getting this error when I submit a card with test info from the _card partial. The error is being generated within CGI.escape, here's the code:

# URL-encode a string.
  #   url_encoded_string = CGI::escape("'Stop!' said Fred")
  #      # => "%27Stop%21%27+said+Fred"
  def CGI::escape(string)
    encoding = string.encoding
    string.dup.force_encoding('ASCII-8BIT').gsub(/([^ a-zA-Z0-9_.-]+)/) do
      '%' + $1.unpack('H2' * $1.bytesize).join('%').upcase
    end.tr(' ', '+').force_encoding(encoding)
  end

I've traced it back a few steps, and I'm pretty sure the error is stemming from the fact that the 'string' being passed in from here:

def retrieve(id, api_key=nil)
      api_key ||= @api_key
      response, api_key = Stripe.request(:get,"#{url}/#{CGI.escape(id)}", api_key)
      Util.convert_to_stripe_object(response, api_key)
    end

is nil. 'retrieve' is called from Koudoku::Subscription#processing:

# store the customer id.
            self.stripe_id = customer.id
            self.last_four = customer.cards.retrieve(customer.default_card).last4
            finalize_new_subscription!
            finalize_upgrade!

It looks like customer.default_card is nil, which is leading to the error. What should this be? Where is it getting set from? Thanks!

**Comment by funkdified** [comment]
I am also experiencing this error.

**Comment by funkdified** [comment]
```
Started POST "/subscriptions/users/3/subscriptions" for 127.0.0.1 at 2015-01-19 11:55:28 -0600
Processing by Koudoku::SubscriptionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"lqefu/e4ks6yrBXNFM5h+j8nKW9yc5gzppf6bQjD5s8=", "subscription"=>{"plan_id"=>"1"}, "owner_id"=>"3"}
  User Load (0.4ms)  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 3  ORDER BY `users`.`id` ASC LIMIT 1
  Subscription Load (0.3ms)  SELECT  `subscriptions`.* FROM `subscriptions`  WHERE `subscriptions`.`user_id` = 3 LIMIT 1
   (0.3ms)  BEGIN
  Plan Load (1.0ms)  SELECT  `plans`.* FROM `plans`  WHERE `plans`.`id` = 1 LIMIT 1
   (0.2ms)  ROLLBACK
Completed 500 Internal Server Error in 627ms

NoMethodError - undefined method `encoding' for nil:NilClass:
   () home/funkdified/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/cgi/util.rb:8:in `escape'
  stripe (1.17.3) lib/stripe/list_object.rb:19:in `retrieve'
  koudoku (0.0.11) app/concerns/koudoku/subscription.rb:95:in `processing!'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:424:in `block in make_lambda'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:160:in `block in halting'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:86:in `run_callbacks'
  activerecord (4.1.7.1) lib/active_record/callbacks.rb:302:in `create_or_update'
  activerecord (4.1.7.1) lib/active_record/persistence.rb:103:in `save'
  activerecord (4.1.7.1) lib/active_record/validations.rb:51:in `save'
  activerecord (4.1.7.1) lib/active_record/attribute_methods/dirty.rb:21:in `save'
  activerecord (4.1.7.1) lib/active_record/transactions.rb:268:in `block (2 levels) in save'
  activerecord (4.1.7.1) lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
  activerecord (4.1.7.1) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
  activerecord (4.1.7.1) lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
  activerecord (4.1.7.1) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
  activerecord (4.1.7.1) lib/active_record/transactions.rb:208:in `transaction'
  activerecord (4.1.7.1) lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
  activerecord (4.1.7.1) lib/active_record/transactions.rb:268:in `block in save'
  activerecord (4.1.7.1) lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
  activerecord (4.1.7.1) lib/active_record/transactions.rb:267:in `save'
  koudoku (0.0.11) app/controllers/koudoku/subscriptions_controller.rb:100:in `create'
  actionpack (4.1.7.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.7.1) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.7.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.7.1) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.7.1) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.7.1) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.7.1) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.7.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.7.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.7.1) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.7.1) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.7.1) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.7.1) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.7.1) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.7.1) lib/action_dispatch/routing/route_set.rb:678:in `call'
  railties (4.1.7.1) lib/rails/engine.rb:514:in `call'
  railties (4.1.7.1) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.1.7.1) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.7.1) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.7.1) lib/action_dispatch/routing/route_set.rb:678:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.7.1) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.7.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.7.1) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.7.1) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.7.1) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.7.1) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.1.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.7.1) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.7.1) lib/rails/engine.rb:514:in `call'
  railties (4.1.7.1) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
  unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
  unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
  unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
  unicorn-rails (2.2.0) lib/unicorn_rails.rb:33:in `run'
  rack (1.5.2) lib/rack/server.rb:264:in `start'
  railties (4.1.7.1) lib/rails/commands/server.rb:69:in `start'
  railties (4.1.7.1) lib/rails/commands/commands_tasks.rb:81:in `block in server'
  railties (4.1.7.1) lib/rails/commands/commands_tasks.rb:76:in `server'
  railties (4.1.7.1) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  railties (4.1.7.1) lib/rails/commands.rb:17:in `<top (required)>'
   () home/funkdified/rails_projects/rails-devise/bin/rails:8:in `<top (required)>'
  spring (1.2.0) lib/spring/client/rails.rb:27:in `call'
  spring (1.2.0) lib/spring/client/command.rb:7:in `call'
  spring (1.2.0) lib/spring/client.rb:26:in `run'
  spring (1.2.0) bin/spring:48:in `<top (required)>'
  spring (1.2.0) lib/spring/binstub.rb:11:in `<top (required)>'
   () home/funkdified/rails_projects/rails-devise/bin/spring:16:in `<top (required)>'
   () rails:3:in `<main>'
```

**Comment by yas4891** [comment]
Have you got turbolinks enabled?

**Comment by funkdified** [comment]
Hi thanks for the response. No I don't. There is no mention of turbolinks in my gemfile.lock

**Comment by funkdified** [comment]
So this demo app was created using rails composer... then koudoku added. 

Check out https://github.com/funkdified/koudoku

**Comment by funkdified** [comment]
There are some major issues here. It seems that the app is allowing me to create subscriptions without entering any CC details. Then when attempting to change the subscription I see the Stripe error message ```This customer has no attached card``` .. which makes sense. Can you please take a look at the simple demo app to see what is wrong? Thanks.

**Comment by funkdified** [comment]
I upgraded to rails 4.2.0 and ruby 2.2.0 today and tried to start over with a fresh test app and following the directions exactly as set forth on the github page. I still ran into a number of issues, and cannot get passed the `encoding` issue... The first problem was the app not recognizing the application helper and not being able to find the `plan_price` method. After fixing this issue, I received the API keys missing error, even after adding them in the manner suggested. I still had to add a stripe initializer and call `rails s` with the keys, as suggested by stripe. Finally, when attempting to submit the credit card form, I run into the encoding issue. I don't understand how this gem can be so broken on a brand spankin new rails-devise install.. What am I missing?  Can you please provide a working test app, or revise the readme to help people use this gem?

**Comment by funkdified** [comment]
While I'm at it.. why was this issue even closed in the first place?

**Comment by yas4891** [comment]
Please try using the github repo instead of the version 0.0.11 - it is out of date. Let me know if this fixes it
