### ISSUE TITLE
subscription redirect for to devise user sign in - NoMethodError 'router_name'

### ISSUE THREAD

**Issue by cdesch** [andrewculver/koudoku#85]
I receive this error when selecting a plan to sign up for:

Started GET "/koudoku/subscriptions/new?plan=2" for 127.0.0.1 at 2014-11-12 14:16:41 -0500
    Processing by Koudoku::SubscriptionsController#new as HTML
      Parameters: {"plan"=>"2"}
    Completed 500 Internal Server Error in 2ms

```
NoMethodError (undefined method `router_name' for nil:NilClass):
  devise (3.3.0) lib/devise/controllers/url_helpers.rb:50:in `new_registration_path'
  koudoku (0.0.11) app/controllers/koudoku/subscriptions_controller.rb:46:in `redirect_to_sign_up'
  koudoku (0.0.11) app/controllers/koudoku/subscriptions_controller.rb:78:in `new'
  actionpack (4.0.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.0.8) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.0.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.0.8) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (4.0.8) lib/active_support/callbacks.rb:443:in `_run__1101018572451401219__process_action__callbacks'
  activesupport (4.0.8) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.8) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (4.0.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.8) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.0.8) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.8) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.0.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.0.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.0.8) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.0.8) lib/abstract_controller/rendering.rb:44:in `process'
  actionpack (4.0.8) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.0.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.0.8) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.0.8) lib/action_dispatch/routing/route_set.rb:82:in `call'
  actionpack (4.0.8) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.0.8) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.0.8) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.8) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.0.8) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.8) lib/action_dispatch/routing/route_set.rb:676:in `call'
  railties (4.0.8) lib/rails/engine.rb:511:in `call'
  railties (4.0.8) lib/rails/railtie/configurable.rb:30:in `method_missing'
  actionpack (4.0.8) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.8) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.0.8) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.8) lib/action_dispatch/routing/route_set.rb:676:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.8) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  activerecord (4.0.8) lib/active_record/migration.rb:373:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.8) lib/active_support/callbacks.rb:373:in `_run__4022916891687647533__call__callbacks'
  activesupport (4.0.8) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/reloader.rb:64:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.8) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.8) lib/rails/engine.rb:511:in `call'
  railties (4.0.8) lib/rails/application.rb:97:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  /Users/cj/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
  /Users/cj/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
  /Users/cj/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

My I believe I have my routes setup properly.

   MyApp::Application.routes.draw do

```
  resources :posts

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  # Added by Koudoku.
  mount Koudoku::Engine, at: 'koudoku'
  scope module: 'koudoku' do
    get 'pricing' => 'subscriptions#index', as: 'pricing'
  end

  root to: 'front_page#index'
  get 'about', to: 'front_page#about'
  get 'tour', to: 'front_page#tour'
end 
```

In the example app at https://koudoku.herokuapp.com, selecting a plan while not logged in redirects to https://koudoku.herokuapp.com/users/sign_up, which is what I want it to do. How can I get the redirection to work properly?

**Comment by philsmy** [comment]
I am having this problem as well. I am already not happy with the amount of app changes needed to use this gem, but, could you tell me what path and where you had to change?

**Comment by yas4891** [comment]
@philsmy for me it most often was a link in the header/footer layout of the app. When you link to a normal model in e.g. your navbar you have to qualify that with `main_app`. 

E.g. 
```
# app/views/layouts/body/_navbar.html.haml
%li#tn_new_campaign= link_to('New Campaign', main_app.new_campaign_url)
```

**Comment by philsmy** [comment]
Actually, I don't think that is the problem. My stack trace starts like this:

`13:28:17 web.1  | NoMethodError (undefined method `router_name' for nil:NilClass):
13:28:17 web.1  |   devise (3.4.1) lib/devise/controllers/url_helpers.rb:50:in `new_registration_path'
13:28:17 web.1  |   /Users/philsmy/.rvm/gems/ruby-2.1.5@zonmaster/bundler/gems/koudoku-44ca7df74cc6/app/controllers/koudoku/subscriptions_controller.rb:67:in `redirect_to_sign_up'
13:28:17 web.1  |   /Users/philsmy/.rvm/gems/ruby-2.1.5@zonmaster/bundler/gems/koudoku-44ca7df74cc6/app/controllers/koudoku/subscriptions_controller.rb:98:in `new'
`

Maybe I need to change something in the devise configuration? Because there is no such thing as 'new_registration_path'. It is 'new_user_registration_path'. But note that User is not our 'owner' object. We are using Milia (https://github.com/dsaronin/milia) for a multi-tenant site.

**Comment by cdesch** [comment]
make sure the `User` is set as `:registerable` in devise config for the `User` model

       devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable

**Comment by Ray-Sutton** [comment]
Hi @cdesch, what link did you fix? Was it one that koudoku create?

**Comment by cdesch** [comment]
@Ray-Sutton I don't recall what the link was that the link would not go to a route because the user was not set as `:registerable` .... it may have been. I think that is what was happening when displaying the pricing table.
