### ISSUE TITLE
Koudoku works great locally but fails in on heroku

### ISSUE THREAD

**Issue by CaptainChemist** [andrewculver/koudoku#92]
This gem works great locally but I am having issues pushing to heroku. The  error I get is:

 heroku[web.1]: State changed from crashed to starting
 heroku[web.1]: Starting process with command `bin/rails server -p 54469 -e production`
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0.beta2/lib/abstract_controller/helpers.rb:144:in `modules_for_helpers'
 app[web.1]: => Booting WEBrick
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/bundler/gems/koudoku-9e73e64e5520/app/controllers/koudoku/application_controller.rb:4:in `<class:ApplicationController>'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0.beta2/lib/rails/engine.rb:465:in `each'
 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:308:in `depend_on'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0.beta2/lib/rails/engine.rb:467:in `block in eager_load!'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0.beta2/lib/rails/commands/commands_tasks.rb:80:in `block in server'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0.beta2/lib/rails/commands/commands_tasks.rb:75:in `tap'
 app[web.1]: 	from bin/rails:8:in `<main>'
 app[web.1]: Exiting
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0.beta2/lib/abstract_controller/helpers.rb:148:in `block in modules_for_helpers'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:248:in `require'
 app[web.1]: 	from /app/config.ru:3:in `block in <main>'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0.beta2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
 app[web.1]: 	from bin/rails:8:in `require'
 app[web.1]: => Run `rails server -h` for more startup options
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0.beta2/lib/abstract_controller/helpers.rb:108:in `helper'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:349:in `require_or_load'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0.beta2/lib/rails/engine.rb:465:in `eager_load!'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0.beta2/lib/rails/application/finisher.rb:56:in `each'
 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0.beta2/lib/rails/commands/server.rb:80:in `start'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0.beta2/lib/rails/commands.rb:17:in `<top (required)>'
 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0.beta2/lib/abstract_controller/helpers.rb:151:in `rescue in block in modules_for_helpers': Missing helper file helpers/application_helper.rb (AbstractController::Helpers::MissingHelperError)
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0.beta2/lib/action_controller/metal/helpers.rb:93:in `modules_for_helpers'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0.beta2/lib/rails/initializable.rb:30:in `run'
 app[web.1]: 	from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
 app[web.1]: 	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:248:in `block in require'

**Comment by CaptainChemist** [comment]
If anyone runs into this issue in the future, I fixed it by adding application_helper.rb to app/helpers:
module ApplicationHelper
end

And also importing the ApplicationHelper in the application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
end

**Comment by guitarjoe02** [comment]
I followed the above instructions and I'm getting a very similar error:

2015-03-01T10:36:49.688131+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 37988 -e production`
2015-03-01T10:36:54.977160+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.4/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `attr_accessible' for #<Class:0x007f19ee7b3108> (NoMethodError)
2015-03-01T10:36:54.936535+00:00 app[web.1]: => Run `rails server -h` for more startup options
2015-03-01T10:36:54.936537+00:00 app[web.1]: => Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
2015-03-01T10:36:54.936533+00:00 app[web.1]: => Rails 4.1.4 application starting in production on http://0.0.0.0:37988
2015-03-01T10:36:54.977176+00:00 app[web.1]: 	from /app/app/models/plan.rb:5:in `<class:Plan>'
2015-03-01T10:36:54.936516+00:00 app[web.1]: => Booting WEBrick
2015-03-01T10:36:54.977178+00:00 app[web.1]: 	from /app/app/models/plan.rb:1:in `<top (required)>'
2015-03-01T10:36:54.936538+00:00 app[web.1]: => Ctrl-C to shutdown server
2015-03-01T10:36:54.936540+00:00 app[web.1]: Exiting
2015-03-01T10:36:54.977180+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
2015-03-01T10:36:54.977184+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
2015-03-01T10:36:54.977185+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
2015-03-01T10:36:54.977182+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
2015-03-01T10:36:54.977188+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:307:in `depend_on'
2015-03-01T10:36:54.977187+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:348:in `require_or_load'
2015-03-01T10:36:54.977199+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/engine.rb:467:in `block in eager_load!'
2015-03-01T10:36:54.977192+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
2015-03-01T10:36:54.977190+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:225:in `require_dependency'
2015-03-01T10:36:54.977203+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/engine.rb:346:in `eager_load!'
2015-03-01T10:36:54.977197+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/engine.rb:467:in `each'
2015-03-01T10:36:54.977202+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/engine.rb:465:in `eager_load!'
2015-03-01T10:36:54.977200+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/engine.rb:465:in `each'
2015-03-01T10:36:54.977207+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'
2015-03-01T10:36:54.977215+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
2015-03-01T10:36:54.977205+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/application/finisher.rb:58:in `each'
2015-03-01T10:36:54.977208+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `instance_exec'
2015-03-01T10:36:54.977212+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `run'
2015-03-01T10:36:54.977220+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
2015-03-01T10:36:54.977223+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
2015-03-01T10:36:54.977216+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
2015-03-01T10:36:54.977214+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/initializable.rb:55:in `block in run_initializers'
2015-03-01T10:36:54.977227+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
2015-03-01T10:36:54.977237+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
2015-03-01T10:36:54.977250+00:00 app[web.1]: 	from /app/config/environment.rb:5:in `<top (required)>'
2015-03-01T10:36:54.977260+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
2015-03-01T10:36:54.977253+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
2015-03-01T10:36:54.977274+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
2015-03-01T10:36:54.977230+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
2015-03-01T10:36:54.977233+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
2015-03-01T10:36:54.977293+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
2015-03-01T10:36:54.977242+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
2015-03-01T10:36:54.977267+00:00 app[web.1]: 	from /app/config.ru:3:in `block in <main>'
2015-03-01T10:36:54.977297+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
2015-03-01T10:36:54.977310+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:81:in `block in server'
2015-03-01T10:36:54.977243+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/initializable.rb:54:in `run_initializers'
2015-03-01T10:36:54.977264+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
2015-03-01T10:36:54.977284+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
2015-03-01T10:36:54.977247+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/application.rb:300:in `initialize!'
2015-03-01T10:36:54.977271+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
2015-03-01T10:36:54.977281+00:00 app[web.1]: 	from /app/config.ru:in `<main>'
2015-03-01T10:36:54.977341+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
2015-03-01T10:36:54.977257+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
2015-03-01T10:36:54.977302+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
2015-03-01T10:36:54.977314+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:76:in `tap'
2015-03-01T10:36:54.977277+00:00 app[web.1]: 	from /app/config.ru:in `new'
2015-03-01T10:36:54.977288+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
2015-03-01T10:36:54.977317+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:76:in `server'
2015-03-01T10:36:54.977335+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
2015-03-01T10:36:54.977343+00:00 app[web.1]: 	from bin/rails:4:in `require'
2015-03-01T10:36:54.977345+00:00 app[web.1]: 	from bin/rails:4:in `<main>'
2015-03-01T10:36:54.977305+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:250:in `start'
2015-03-01T10:36:54.977298+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/commands/server.rb:50:in `app'
2015-03-01T10:36:54.977289+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
2015-03-01T10:36:54.977309+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.4/lib/rails/commands/server.rb:69:in `start'
2015-03-01T10:36:55.930696+00:00 heroku[web.1]: Process exited with status 1
2015-03-01T10:36:55.949258+00:00 heroku[web.1]: State changed from starting to crashed
2015-03-01T10:36:57.199189+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=accelcoder.com request_id=2df04051-0e6a-41fa-bf8f-a667899ab905 fwd="199.83.125.10" dyno= connect= service= status=503 bytes=

Any help you can provide?

**Comment by CaptainChemist** [comment]
Hi GuitarJoe, I am not exactly sure your issue, but a clue to look at is at the beginning:
method_missing': undefined methodattr_accessible'
the attr_accessible is a Rails 3 thing so if you are trying to use rails 4, you need to upgrade the strong parameters notation:
http://stackoverflow.com/questions/17371334/how-is-attr-accessible-used-in-rails-4

**Comment by guitarjoe02** [comment]
Thanks for the reply... I forgot to close the loop. I implemented the [Protected Attributes] (https://github.com/rails/protected_attributes) and was able to get the system up.

Unfortunately, that required that I add attr_accessible to all of my other models too.

But, I'm up an running.

Thanks!
